# Generated by Django 4.1.3 on 2023-02-28 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('surcharge_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Surcharge Percentage')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Shipment Code')),
                ('origin_city', models.CharField(max_length=150, verbose_name='Origin City')),
                ('origin_country', models.CharField(max_length=150, verbose_name='Origin Country')),
                ('destination_city', models.CharField(max_length=150, verbose_name='Destination City')),
                ('destination_country', models.CharField(max_length=150, verbose_name='Destination Country')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Base Price')),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Surcharge Name')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Surcharge Percentage')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Surcharge Amount')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'surcharges',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tax Name')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tax Percentage')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'taxes',
            },
        ),
        migrations.CreateModel(
            name='TaxShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fedex.shipment')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fedex.tax')),
            ],
            options={
                'db_table': 'shipment_taxes',
            },
        ),
        migrations.CreateModel(
            name='SurchargeShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fedex.shipment')),
                ('surcharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fedex.surcharge')),
            ],
            options={
                'db_table': 'shipment_surcharges',
            },
        ),
        migrations.CreateModel(
            name='ShipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fedex.category')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fedex.shipment')),
            ],
            options={
                'db_table': 'shipment_categories',
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='categories',
            field=models.ManyToManyField(through='fedex.ShipmentCategory', to='fedex.category'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='surcharges',
            field=models.ManyToManyField(through='fedex.SurchargeShipment', to='fedex.surcharge'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='taxes',
            field=models.ManyToManyField(through='fedex.TaxShipment', to='fedex.tax'),
        ),
    ]
