# Generated by Django 4.1.3 on 2023-02-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='percentage',
        ),
        migrations.DeleteModel(
            name='TaxShipment',
        ),
    ]
