# Generated by Django 4.1.3 on 2023-02-28 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedex', '0002_remove_shipment_taxes_remove_surcharge_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentTaxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Tax Amount')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fedex.shipment')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fedex.tax')),
            ],
            options={
                'db_table': 'shipment_taxes',
            },
        ),
    ]
