# Generated by Django 4.1.3 on 2023-02-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedex', '0003_shipmenttaxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Taxes'),
        ),
        migrations.DeleteModel(
            name='ShipmentTaxes',
        ),
    ]
